# Netlify configuration for Resume Optimizer Chatbot
[build]
  # Build command for Next.js frontend
  command = "cd frontend && npm ci && npm run build"
  
  # Directory to publish (Next.js output)
  publish = "frontend/out"
  
  # Base directory
  base = "/"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js specific environment
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect all API calls to external backend (you'll need to deploy backend separately)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = false

# Handle Next.js routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_API_URL = "https://your-backend-url.herokuapp.com"
# NEXT_PUBLIC_WS_URL = "wss://your-backend-url.herokuapp.com"